// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/DENet.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// DENet
arma::sp_mat DENet(arma::sp_mat& G0, arma::mat& A, arma::uvec x, arma::uvec y, bool logpval_weights, double min_pval);
RcppExport SEXP _DENet_DENet(SEXP G0SEXP, SEXP ASEXP, SEXP xSEXP, SEXP ySEXP, SEXP logpval_weightsSEXP, SEXP min_pvalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type G0(G0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type logpval_weights(logpval_weightsSEXP);
    Rcpp::traits::input_parameter< double >::type min_pval(min_pvalSEXP);
    rcpp_result_gen = Rcpp::wrap(DENet(G0, A, x, y, logpval_weights, min_pval));
    return rcpp_result_gen;
END_RCPP
}
// DENet_full
arma::mat DENet_full(arma::mat& A, arma::uvec x, arma::uvec y, double min_pval);
RcppExport SEXP _DENet_DENet_full(SEXP ASEXP, SEXP xSEXP, SEXP ySEXP, SEXP min_pvalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type min_pval(min_pvalSEXP);
    rcpp_result_gen = Rcpp::wrap(DENet_full(A, x, y, min_pval));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DENet_DENet", (DL_FUNC) &_DENet_DENet, 6},
    {"_DENet_DENet_full", (DL_FUNC) &_DENet_DENet_full, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_DENet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
