// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/DENet.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// F2z
double F2z(double F, double d1, double d2);
RcppExport SEXP _DENet_F2z(SEXP FSEXP, SEXP d1SEXP, SEXP d2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type F(FSEXP);
    Rcpp::traits::input_parameter< double >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< double >::type d2(d2SEXP);
    rcpp_result_gen = Rcpp::wrap(F2z(F, d1, d2));
    return rcpp_result_gen;
END_RCPP
}
// T2z
double T2z(double T, double nx, double ny, double p);
RcppExport SEXP _DENet_T2z(SEXP TSEXP, SEXP nxSEXP, SEXP nySEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< double >::type ny(nySEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(T2z(T, nx, ny, p));
    return rcpp_result_gen;
END_RCPP
}
// DENet
arma::sp_mat DENet(arma::sp_mat& G0, arma::mat& A, arma::uvec x, arma::uvec y, int normalization);
RcppExport SEXP _DENet_DENet(SEXP G0SEXP, SEXP ASEXP, SEXP xSEXP, SEXP ySEXP, SEXP normalizationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type G0(G0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type normalization(normalizationSEXP);
    rcpp_result_gen = Rcpp::wrap(DENet(G0, A, x, y, normalization));
    return rcpp_result_gen;
END_RCPP
}
// DENet_full
arma::mat DENet_full(arma::mat& A, arma::uvec x, arma::uvec y, int normalization);
RcppExport SEXP _DENet_DENet_full(SEXP ASEXP, SEXP xSEXP, SEXP ySEXP, SEXP normalizationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type normalization(normalizationSEXP);
    rcpp_result_gen = Rcpp::wrap(DENet_full(A, x, y, normalization));
    return rcpp_result_gen;
END_RCPP
}
// kStarNN
arma::sp_mat kStarNN(arma::mat G, int sim2dist, double LC);
RcppExport SEXP _DENet_kStarNN(SEXP GSEXP, SEXP sim2distSEXP, SEXP LCSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type G(GSEXP);
    Rcpp::traits::input_parameter< int >::type sim2dist(sim2distSEXP);
    Rcpp::traits::input_parameter< double >::type LC(LCSEXP);
    rcpp_result_gen = Rcpp::wrap(kStarNN(G, sim2dist, LC));
    return rcpp_result_gen;
END_RCPP
}
// symmetrize_network
arma::sp_mat symmetrize_network(arma::sp_mat G, int sym);
RcppExport SEXP _DENet_symmetrize_network(SEXP GSEXP, SEXP symSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type G(GSEXP);
    Rcpp::traits::input_parameter< int >::type sym(symSEXP);
    rcpp_result_gen = Rcpp::wrap(symmetrize_network(G, sym));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DENet_F2z", (DL_FUNC) &_DENet_F2z, 3},
    {"_DENet_T2z", (DL_FUNC) &_DENet_T2z, 4},
    {"_DENet_DENet", (DL_FUNC) &_DENet_DENet, 5},
    {"_DENet_DENet_full", (DL_FUNC) &_DENet_DENet_full, 4},
    {"_DENet_kStarNN", (DL_FUNC) &_DENet_kStarNN, 3},
    {"_DENet_symmetrize_network", (DL_FUNC) &_DENet_symmetrize_network, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_DENet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
