# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DENet <- function(G0, A, x, y, logpval_weights = FALSE, normalization = 1L) {
    .Call(`_DENet_DENet`, G0, A, x, y, logpval_weights, normalization)
}

DENet_full <- function(A, x, y, normalization = 1L) {
    .Call(`_DENet_DENet_full`, A, x, y, normalization)
}

kStarNN <- function(G, sim2dist = 2L, LC = 1, sym = 2L) {
    .Call(`_DENet_kStarNN`, G, sim2dist, LC, sym)
}

