# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DENet <- function(G0, A, x, y, logpval_weights = FALSE, min_pval = 1e-300) {
    .Call(`_DENet_DENet`, G0, A, x, y, logpval_weights, min_pval)
}

DENet_full <- function(A, x, y, min_pval = 1e-300) {
    .Call(`_DENet_DENet_full`, A, x, y, min_pval)
}

